### ISSUE TITLE
Possibility to accept old SSL versions?

### ISSUE THREAD

**Issue by kontr0x** [ross/requests-futures#107] opened 2021-06-10 08:14 UTC
I am already using `verify=False` in my sessions as an argument, but still I am getting this error message:

`Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)')))`

Any fix or help for this issue is welcomed

**Comment by ross** [comment] 2021-06-10 20:58
That error will be more of a `requests` thing and not anything specifically to do with `requests_futures`. 

My first guess is that there's a mis-match in TLS versions supported by your client and the server. You may be able to turn up debug logging for requests/urllib3 (everything really) to get more information about what's going wrong.

Otherwise try googling for `python requests "Max retries exceeded with url: / (Caused by SSLError(SSLError"`. There's lots of results with a number of different potential causes. You might also try looking through `requests` repo's issues.

Closing since this isn't directly to do with this module.

**Closed by ross** 2021-06-10 20:58 UTC
