### ISSUE TITLE
KeyboardInterrupt doesn't stop program, it just sit there half dead

### ISSUE THREAD

**Issue by shaleh** [ross/requests-futures#14] opened 2014-07-16 00:57 UTC
I have the usual try/except for KeyboardInterrupt around my main which raises SystemExit. But the program doesn't die. While searching the web I see various solutions for Python Threads but this is not exposed by this library. What is the best practice for handling signals in Requests_Futures?

**Comment by hcarvalhoalves** [comment] 2015-06-26 15:36
@shaleh if you're using the Python 2 backport of Futures, this is due to the Futures implementation not catching KeyboardInterrupt.

https://github.com/agronholm/pythonfutures/issues/25

This is not fixable from `requests-futures`.

**Comment by ross** [comment] 2015-06-26 15:40
awesome @hcarvalhoalves, thanks for linking them up. i'll close this one now that people will be pointed to the root cause.

**Closed by ross** 2015-06-26 15:40 UTC
